import UIKit

let SOLT_COLOR_HEX: String = "#06244B"
let SOLT_COLOR = UIColor(hex: SOLT_COLOR_HEX)

let VEGAN_COLOR_HEX: String = "#289900"
let VEGAN_COLOR = UIColor(hex: VEGAN_COLOR_HEX)

let NONVEGAN_COLOR_HEX: String = "#8E0201"
let NONVEGAN_COLOR = UIColor(hex: NONVEGAN_COLOR_HEX)
